#!/bin/bash
# Managed by Terraform

set -e -u -o pipefail

floaty_bin=/usr/bin/floaty
log_name=keepalived-floaty-eth1
config_file=/etc/floaty/config.yaml

"$floaty_bin" "$config_file" "$@" 2>&1 | logger --tag "$log_name"
