name: Pull Request
on:
  pull_request:
    branches:
    - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.10
      - run: terraform fmt -check -recursive
      - run: terraform init -input=false
      - run: terraform validate
